apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dipenkalal/enterprise-gitops.git
    path: apps/java-app
    targetRevision: main
    helm:
      valueFiles:
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
