apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app.kubernetes.io/name: java-app
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: java-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-app
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet: { path: /actuator/health, port: http }
          initialDelaySeconds: 5
        livenessProbe:
          httpGet: { path: /actuator/health, port: http }
          initialDelaySeconds: 10
        resources:
          requests: { cpu: 100m, memory: 256Mi }
          limits:   { cpu: 500m, memory: 512Mi }
