apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: java-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-app
  minReplicas: {{ .Values.hpa.min | default 1 }}
  maxReplicas: {{ .Values.hpa.max | default 3 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpu | default 70 }}
