apiVersion: v1
kind: Service
metadata:
  name: java-app
  labels:
    app.kubernetes.io/name: java-app
spec:
  selector:
    app.kubernetes.io/name: java-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
