apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-app
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: java-app
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
